name: IntegraciÃ³n continua
on:
  push:
    branches:
      - develop
jobs:
  setup-build:
    name: Configurar, Construir
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.CGP_PROJECT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate json
        env:
          KEY: ${{ secrets.GCP_KEY }}
        run: |
          printf $KEY > key.json

      - name: Build Test
        env:
          MONGO_URI: "mongodb://localhost:27017/hrapp_dev"
          PORT: "3000"
          HOST_NAME: "localhost"
          JWT_SECRET: "TEST"
        run: |
          chmod +x ./gradlew
          ./gradlew build